<div class="container">
    <div class="page-header">
        <h1>Welcome to Zf-Hipsters Authorize Installer</h1>
    </div>
    <p class="lead">To make this EXTRA simple, we're going to guide you through the installation of this module.</p>

    <h4>Installation Progress</h4>
    <div class="progress progress-striped">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            <span class="sr-only">0% Complete (success)</span>
        </div>
    </div>

    <p>Please ensure the following folders are writeable. Then click Install below.<br/>(You may reset the permissions after installation is complete)</p>
    <table class="table table-striped" role="table">
        <thead>
        <tr>
            <th>Folder</th>
            <th style="text-align: center;">Writeable?</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <?php foreach ($paths as $path):?>
            <td><i class="glyphicon glyphicon-folder-open"></i>&nbsp;&nbsp;&nbsp;<?=$path['path']?></td>
            <td style="text-align: center;">
                <?php if ($path['writeable'] == true):?>
                    <i class="glyphicon glyphicon-check" style="color:green"></i>
                <?php else:?>
                    <i class="glyphicon glyphicon-remove" style="color:red"></i>
                <?php endif;?>
            </td>
            <?php endforeach;?>
        </tr>
        </tbody>
    </table>
    <?php if ($install):?>
    <a href="<?=$this->url('authorize_install', array('action'=>'db'))?>" class="btn btn-success">Install</a>
    <?php else: ?>
        <a href="<?=$this->url('authorize_install')?>" class="btn btn-danger">Retry</a>
    <?php endif;?>
</div>